version: "2"

linters:
  enable:
    - bodyclose
    - errorlint
    - gosec
    - misspell
    - nilerr
    - noctx
    - nolintlint
    - revive

formatters:
  enable:
    - gofmt
    - goimports
  settings:
    gofmt:
      simplify: true
    goimports:
      local-prefixes:
        - github.com/sunfish-robotics/ulog
